import {
  Users,
  Activity,
  Calendar,
  FileText,
  Settings,
  BarChart3,
  Brain,
  Target,
  ShoppingCart,
  Receipt,
  Package,
  Mail,
  TrendingUp,
  Plus,
} from 'lucide-react'
import type { AdminConfig } from '@vertigo/admin'

export const teamBuildingAdminConfig: AdminConfig = {
  vertical: 'TEAM_BUILDING',
  productName: 'TeamForge',
  productIcon: Users,
  gradient: 'from-sky-400 to-blue-500',
  basePath: '/admin',
  storageKeyPrefix: 'teamforge',
  breadcrumbLabels: {
    admin: 'Dashboard',
    programs: 'Programs',
    activities: 'Activities',
    sessions: 'Sessions',
    customers: 'Customers',
    orders: 'Orders',
    invoices: 'Invoices',
    extras: 'Extras',
    reports: 'Reports',
    analytics: 'Analytics',
    settings: 'Settings',
    ai: 'AI Tools',
    'team-analysis': 'Team Analysis',
    'objective-matcher': 'Objective Matcher',
    'email-sequences': 'Email Sequences',
    new: 'New',
  },
  navigation: [
    { name: 'Dashboard', href: '/admin', icon: BarChart3 },
    { name: 'Programs', href: '/admin/programs', icon: Users },
    { name: 'Activities', href: '/admin/activities', icon: Activity },
    { name: 'Sessions', href: '/admin/sessions', icon: Calendar },
    { name: 'Customers', href: '/admin/customers', icon: Users },
    {
      name: 'Sales',
      icon: ShoppingCart,
      children: [
        { name: 'Orders', href: '/admin/orders', icon: ShoppingCart },
        { name: 'Invoices', href: '/admin/invoices', icon: Receipt },
        { name: 'Extras', href: '/admin/extras', icon: Package },
      ],
    },
    { name: 'Reports', href: '/admin/reports', icon: FileText },
    { name: 'Analytics', href: '/admin/analytics', icon: TrendingUp },
    {
      name: 'Marketing',
      icon: Mail,
      children: [
        { name: 'Email Sequences', href: '/admin/email-sequences', icon: Mail },
      ],
    },
    {
      name: 'AI Tools',
      icon: Brain,
      children: [
        { name: 'Team Analysis', href: '/admin/ai/team-analysis', icon: Brain },
        { name: 'Objective Matcher', href: '/admin/ai/objective-matcher', icon: Target },
      ],
    },
    { name: 'Settings', href: '/admin/settings', icon: Settings },
  ],
  commandGroups: ['Pages', 'Actions', 'AI Tools'],
  commands: [
    { id: 'dashboard', label: 'Dashboard', icon: BarChart3, href: '/admin', group: 'Pages' },
    { id: 'programs', label: 'Programs', icon: Users, href: '/admin/programs', group: 'Pages' },
    { id: 'activities', label: 'Activities', icon: Activity, href: '/admin/activities', group: 'Pages' },
    { id: 'sessions', label: 'Sessions', icon: Calendar, href: '/admin/sessions', group: 'Pages' },
    { id: 'customers', label: 'Customers', icon: Users, href: '/admin/customers', group: 'Pages' },
    { id: 'orders', label: 'Orders', icon: ShoppingCart, href: '/admin/orders', group: 'Pages' },
    { id: 'invoices', label: 'Invoices', icon: Receipt, href: '/admin/invoices', group: 'Pages' },
    { id: 'extras', label: 'Extras', icon: Package, href: '/admin/extras', group: 'Pages' },
    { id: 'reports', label: 'Reports', icon: FileText, href: '/admin/reports', group: 'Pages' },
    { id: 'analytics', label: 'Analytics', icon: TrendingUp, href: '/admin/analytics', group: 'Pages' },
    { id: 'email-sequences', label: 'Email Sequences', icon: Mail, href: '/admin/email-sequences', group: 'Pages' },
    { id: 'settings', label: 'Settings', icon: Settings, href: '/admin/settings', group: 'Pages' },
    { id: 'new-program', label: 'Create Program', icon: Plus, href: '/admin/programs/new', group: 'Actions', keywords: ['new', 'add'] },
    { id: 'new-activity', label: 'Add Activity', icon: Plus, href: '/admin/activities/new', group: 'Actions', keywords: ['new', 'create'] },
    { id: 'new-session', label: 'Schedule Session', icon: Plus, href: '/admin/sessions/new', group: 'Actions', keywords: ['new', 'create', 'book'] },
    { id: 'new-customer', label: 'Add Customer', icon: Plus, href: '/admin/customers/new', group: 'Actions', keywords: ['new', 'create'] },
    { id: 'team-analysis', label: 'Team Analysis', icon: Brain, href: '/admin/ai/team-analysis', group: 'AI Tools', keywords: ['ai', 'analyze'] },
    { id: 'objective-matcher', label: 'Objective Matcher', icon: Target, href: '/admin/ai/objective-matcher', group: 'AI Tools', keywords: ['ai', 'match'] },
  ],
}
