import {
  LayoutDashboard,
  Clapperboard,
  Calendar,
  Users,
  Building2,
  FileText,
  Package,
  Settings,
  Plus,
} from 'lucide-react'
import type { AdminConfig } from '@vertigo/admin'

export const performingArtsAdminConfig: AdminConfig = {
  vertical: 'PERFORMING_ARTS',
  productName: 'StageManager',
  productIcon: Clapperboard,
  gradient: 'from-red-500 to-rose-600',
  basePath: '/admin',
  storageKeyPrefix: 'stagemanager',
  breadcrumbLabels: {
    admin: 'Dashboard',
    productions: 'Productions',
    rehearsals: 'Rehearsals',
    'tech-riders': 'Tech Riders',
    venues: 'Venues',
    'cast-crew': 'Cast & Crew',
    equipment: 'Equipment',
    settings: 'Settings',
    new: 'New',
  },
  navigation: [
    { name: 'Dashboard', href: '/admin', icon: LayoutDashboard },
    { name: 'Productions', href: '/admin/productions', icon: Clapperboard },
    { name: 'Rehearsals', href: '/admin/rehearsals', icon: Calendar },
    { name: 'Cast & Crew', href: '/admin/cast-crew', icon: Users },
    { name: 'Venues', href: '/admin/venues', icon: Building2 },
    { name: 'Tech Riders', href: '/admin/tech-riders', icon: FileText },
    { name: 'Equipment', href: '/admin/equipment', icon: Package },
    { name: 'Settings', href: '/admin/settings', icon: Settings },
  ],
  commandGroups: ['Pages', 'Actions'],
  commands: [
    { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, href: '/admin', group: 'Pages' },
    { id: 'productions', label: 'Productions', icon: Clapperboard, href: '/admin/productions', group: 'Pages' },
    { id: 'rehearsals', label: 'Rehearsals', icon: Calendar, href: '/admin/rehearsals', group: 'Pages' },
    { id: 'cast-crew', label: 'Cast & Crew', icon: Users, href: '/admin/cast-crew', group: 'Pages' },
    { id: 'venues', label: 'Venues', icon: Building2, href: '/admin/venues', group: 'Pages' },
    { id: 'tech-riders', label: 'Tech Riders', icon: FileText, href: '/admin/tech-riders', group: 'Pages' },
    { id: 'equipment', label: 'Equipment', icon: Package, href: '/admin/equipment', group: 'Pages' },
    { id: 'settings', label: 'Settings', icon: Settings, href: '/admin/settings', group: 'Pages' },
    { id: 'new-production', label: 'Create Production', icon: Plus, href: '/admin/productions/new', group: 'Actions', keywords: ['new', 'add', 'create'] },
  ],
}
