import {
  PartyPopper,
  LayoutDashboard,
  Package,
  Puzzle,
  Gift,
  Calendar,
  Users,
  ShoppingCart,
  FileText,
  Sparkles,
  Settings,
  Plus,
} from 'lucide-react'
import type { AdminConfig } from '@vertigo/admin'

export const kidsEntertainmentAdminConfig: AdminConfig = {
  vertical: 'KIDS_ENTERTAINMENT',
  productName: 'PartyPal',
  productIcon: PartyPopper,
  gradient: 'from-pink-400 to-rose-500',
  basePath: '/admin',
  storageKeyPrefix: 'partypal',
  breadcrumbLabels: {
    admin: 'Dashboard',
    packages: 'Balíčky',
    activities: 'Aktivity',
    extras: 'Extra doplňky',
    parties: 'Oslavy',
    customers: 'Zákazníci',
    orders: 'Objednávky',
    invoices: 'Faktury',
    entertainers: 'Animátoři',
    settings: 'Nastavení',
    new: 'Nový',
    login: 'Přihlášení',
  },
  navigation: [
    { name: 'Dashboard', href: '/admin', icon: LayoutDashboard },
    { name: 'Balíčky', href: '/admin/packages', icon: Package },
    { name: 'Aktivity', href: '/admin/activities', icon: Puzzle },
    { name: 'Extra doplňky', href: '/admin/extras', icon: Gift },
    { name: 'Oslavy', href: '/admin/parties', icon: Calendar },
    { name: 'Zákazníci', href: '/admin/customers', icon: Users },
    { name: 'Objednávky', href: '/admin/orders', icon: ShoppingCart },
    { name: 'Faktury', href: '/admin/invoices', icon: FileText },
    { name: 'Animátoři', href: '/admin/entertainers', icon: Sparkles },
    { name: 'Nastavení', href: '/admin/settings', icon: Settings },
  ],
  commandGroups: ['Stránky', 'Akce'],
  commands: [
    { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, href: '/admin', group: 'Stránky' },
    { id: 'packages', label: 'Balíčky', icon: Package, href: '/admin/packages', group: 'Stránky' },
    { id: 'activities', label: 'Aktivity', icon: Puzzle, href: '/admin/activities', group: 'Stránky' },
    { id: 'extras', label: 'Extra doplňky', icon: Gift, href: '/admin/extras', group: 'Stránky' },
    { id: 'parties', label: 'Oslavy', icon: Calendar, href: '/admin/parties', group: 'Stránky' },
    { id: 'customers', label: 'Zákazníci', icon: Users, href: '/admin/customers', group: 'Stránky' },
    { id: 'orders', label: 'Objednávky', icon: ShoppingCart, href: '/admin/orders', group: 'Stránky' },
    { id: 'invoices', label: 'Faktury', icon: FileText, href: '/admin/invoices', group: 'Stránky' },
    { id: 'entertainers', label: 'Animátoři', icon: Sparkles, href: '/admin/entertainers', group: 'Stránky' },
    { id: 'settings', label: 'Nastavení', icon: Settings, href: '/admin/settings', group: 'Stránky' },
    { id: 'new-package', label: 'Nový balíček', icon: Plus, href: '/admin/packages/new', group: 'Akce', keywords: ['new', 'add', 'nový'] },
    { id: 'new-activity', label: 'Nová aktivita', icon: Plus, href: '/admin/activities/new', group: 'Akce', keywords: ['new', 'add', 'nová'] },
  ],
}
