import {
  Camera,
  Package,
  Calendar,
  ListChecks,
  Images,
  Users,
  FileText,
  FileSignature,
  Settings,
  Plus,
  LayoutDashboard,
} from 'lucide-react'
import type { AdminConfig } from '@vertigo/admin'

export const photographyAdminConfig: AdminConfig = {
  vertical: 'PHOTOGRAPHY',
  productName: 'ShootFlow',
  productIcon: Camera,
  gradient: 'from-amber-400 to-orange-500',
  basePath: '/admin',
  storageKeyPrefix: 'shootflow',
  breadcrumbLabels: {
    admin: 'Dashboard',
    packages: 'Packages',
    shoots: 'Shoots',
    'shot-lists': 'Shot Lists',
    galleries: 'Galleries',
    clients: 'Clients',
    contracts: 'Contracts',
    invoices: 'Invoices',
    calendar: 'Calendar',
    settings: 'Settings',
    new: 'New',
    edit: 'Edit',
    upload: 'Upload',
  },
  navigation: [
    { name: 'Dashboard', href: '/admin', icon: LayoutDashboard },
    { name: 'Packages', href: '/admin/packages', icon: Package },
    { name: 'Shoots', href: '/admin/shoots', icon: Calendar },
    { name: 'Shot Lists', href: '/admin/shot-lists', icon: ListChecks },
    { name: 'Galleries', href: '/admin/galleries', icon: Images },
    { name: 'Clients', href: '/admin/clients', icon: Users },
    { name: 'Contracts', href: '/admin/contracts', icon: FileSignature },
    { name: 'Invoices', href: '/admin/invoices', icon: FileText },
    { name: 'Settings', href: '/admin/settings', icon: Settings },
  ],
  commandGroups: ['Pages', 'Actions'],
  commands: [
    { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, href: '/admin', group: 'Pages' },
    { id: 'packages', label: 'Packages', icon: Package, href: '/admin/packages', group: 'Pages' },
    { id: 'shoots', label: 'Shoots', icon: Calendar, href: '/admin/shoots', group: 'Pages' },
    { id: 'shot-lists', label: 'Shot Lists', icon: ListChecks, href: '/admin/shot-lists', group: 'Pages' },
    { id: 'galleries', label: 'Galleries', icon: Images, href: '/admin/galleries', group: 'Pages' },
    { id: 'clients', label: 'Clients', icon: Users, href: '/admin/clients', group: 'Pages' },
    { id: 'contracts', label: 'Contracts', icon: FileSignature, href: '/admin/contracts', group: 'Pages' },
    { id: 'invoices', label: 'Invoices', icon: FileText, href: '/admin/invoices', group: 'Pages' },
    { id: 'calendar', label: 'Calendar', icon: Calendar, href: '/admin/calendar', group: 'Pages' },
    { id: 'settings', label: 'Settings', icon: Settings, href: '/admin/settings', group: 'Pages' },
    { id: 'new-shoot', label: 'New Shoot', icon: Plus, href: '/admin/shoots/new', group: 'Actions', keywords: ['create', 'add'] },
    { id: 'new-client', label: 'New Client', icon: Plus, href: '/admin/clients/new', group: 'Actions', keywords: ['create', 'add'] },
    { id: 'new-gallery', label: 'New Gallery', icon: Plus, href: '/admin/galleries/new', group: 'Actions', keywords: ['create', 'add'] },
    { id: 'new-contract', label: 'New Contract', icon: Plus, href: '/admin/contracts/new', group: 'Actions', keywords: ['create', 'add'] },
    { id: 'new-invoice', label: 'New Invoice', icon: Plus, href: '/admin/invoices/new', group: 'Actions', keywords: ['create', 'add'] },
  ],
}
