import {
  Music,
  Calendar,
  List,
  Users,
  FileText,
  Sparkles,
  Settings,
  CreditCard,
  Inbox,
  Plus,
  LayoutDashboard,
  FileSignature,
} from 'lucide-react'
import type { AdminConfig } from '@vertigo/admin'

export const musiciansAdminConfig: AdminConfig = {
  vertical: 'MUSICIANS',
  productName: 'GigBook',
  productIcon: Music,
  gradient: 'from-violet-500 to-purple-600',
  basePath: '/admin',
  storageKeyPrefix: 'gigbook',
  breadcrumbLabels: {
    admin: 'Dashboard',
    gigs: 'Gigs',
    inquiries: 'Inquiries',
    setlists: 'Setlists',
    repertoire: 'Repertoire',
    clients: 'Clients',
    invoices: 'Invoices',
    contracts: 'Contracts',
    billing: 'Billing',
    settings: 'Settings',
    payments: 'Payments',
    new: 'New',
    edit: 'Edit',
    generate: 'Generate',
    import: 'Import',
    reconciliation: 'Reconciliation',
    widget: 'Widget',
    reminders: 'Reminders',
    pricing: 'Pricing',
  },
  navigation: [
    { name: 'Dashboard', href: '/admin', icon: LayoutDashboard },
    { name: 'Gigs', href: '/admin/gigs', icon: Music },
    { name: 'Inquiries', href: '/admin/inquiries', icon: Inbox },
    { name: 'Setlists', href: '/admin/setlists', icon: List },
    { name: 'Repertoire', href: '/admin/repertoire', icon: Sparkles },
    { name: 'Clients', href: '/admin/clients', icon: Users },
    { name: 'Invoices', href: '/admin/invoices', icon: FileText },
    { name: 'Contracts', href: '/admin/contracts', icon: FileSignature },
    { name: 'Billing', href: '/admin/billing', icon: CreditCard },
    { name: 'Settings', href: '/admin/settings', icon: Settings },
  ],
  commandGroups: ['Pages', 'Actions'],
  commands: [
    { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, href: '/admin', group: 'Pages' },
    { id: 'gigs', label: 'Gigs', icon: Music, href: '/admin/gigs', group: 'Pages' },
    { id: 'inquiries', label: 'Inquiries', icon: Inbox, href: '/admin/inquiries', group: 'Pages' },
    { id: 'setlists', label: 'Setlists', icon: List, href: '/admin/setlists', group: 'Pages' },
    { id: 'repertoire', label: 'Repertoire', icon: Sparkles, href: '/admin/repertoire', group: 'Pages' },
    { id: 'clients', label: 'Clients', icon: Users, href: '/admin/clients', group: 'Pages' },
    { id: 'invoices', label: 'Invoices', icon: FileText, href: '/admin/invoices', group: 'Pages' },
    { id: 'contracts', label: 'Contracts', icon: FileSignature, href: '/admin/contracts', group: 'Pages' },
    { id: 'billing', label: 'Billing', icon: CreditCard, href: '/admin/billing', group: 'Pages' },
    { id: 'settings', label: 'Settings', icon: Settings, href: '/admin/settings', group: 'Pages' },
    { id: 'new-gig', label: 'New Gig', icon: Plus, href: '/admin/gigs/new', group: 'Actions', keywords: ['create', 'add'] },
    { id: 'new-setlist', label: 'New Setlist', icon: Plus, href: '/admin/setlists/new', group: 'Actions', keywords: ['create', 'add'] },
    { id: 'new-client', label: 'New Client', icon: Plus, href: '/admin/clients/new', group: 'Actions', keywords: ['create', 'add'] },
    { id: 'generate-setlist', label: 'Generate Setlist', icon: Sparkles, href: '/admin/setlists/generate', group: 'Actions', keywords: ['ai', 'generate'] },
  ],
}
