import {
  Home,
  Users,
  Calendar,
  Dumbbell,
  Package,
  FileText,
  Settings,
  TrendingUp,
  LayoutGrid,
  BarChart3,
  FileBarChart,
  Receipt,
  ClipboardList,
  CalendarClock,
  Gift,
  RefreshCw,
  Mail,
  Plus,
} from 'lucide-react'
import type { AdminConfig } from '@vertigo/admin'

export const fitnessAdminConfig: AdminConfig = {
  vertical: 'FITNESS',
  productName: 'FitAdmin',
  productIcon: Dumbbell,
  gradient: 'from-emerald-400 to-teal-500',
  basePath: '/admin',
  storageKeyPrefix: 'fitadmin',
  breadcrumbLabels: {
    admin: 'Dashboard',
    clients: 'Klienti',
    progress: 'Progress',
    referrals: 'Doporučení',
    sessions: 'Sessions',
    classes: 'Skupinové lekce',
    packages: 'Balíčky',
    subscriptions: 'Předplatné',
    invoices: 'Faktury',
    expenses: 'Výdaje',
    analytics: 'Analytika',
    reports: 'Reporty',
    'email-sequences': 'Email sekvence',
    templates: 'Šablony tréninků',
    'schedule-templates': 'Šablony rozvrhu',
    settings: 'Nastavení',
    billing: 'Platby',
    payments: 'Platby',
    new: 'Nový',
  },
  navigation: [
    { name: 'Dashboard', href: '/admin', icon: Home },
    {
      name: 'Klienti',
      icon: Users,
      children: [
        { name: 'Klienti', href: '/admin/clients', icon: Users },
        { name: 'Progress', href: '/admin/progress', icon: TrendingUp },
        { name: 'Doporučení', href: '/admin/referrals', icon: Gift },
      ],
    },
    {
      name: 'Tréninky',
      icon: Calendar,
      children: [
        { name: 'Sessions', href: '/admin/sessions', icon: Calendar },
        { name: 'Skupinové lekce', href: '/admin/classes', icon: LayoutGrid },
      ],
    },
    {
      name: 'Obchod',
      icon: Package,
      children: [
        { name: 'Balíčky', href: '/admin/packages', icon: Package },
        { name: 'Předplatné', href: '/admin/subscriptions', icon: RefreshCw },
        { name: 'Faktury', href: '/admin/invoices', icon: FileText },
        { name: 'Výdaje', href: '/admin/expenses', icon: Receipt },
      ],
    },
    {
      name: 'Analytika',
      icon: BarChart3,
      children: [
        { name: 'Přehled', href: '/admin/analytics', icon: BarChart3 },
        { name: 'Reporty', href: '/admin/reports', icon: FileBarChart },
      ],
    },
    {
      name: 'Marketing',
      icon: Mail,
      children: [
        { name: 'Email sekvence', href: '/admin/email-sequences', icon: Mail },
      ],
    },
    {
      name: 'Knihovna',
      icon: ClipboardList,
      children: [
        { name: 'Šablony tréninků', href: '/admin/templates', icon: ClipboardList },
        { name: 'Šablony rozvrhu', href: '/admin/schedule-templates', icon: CalendarClock },
      ],
    },
    { name: 'Nastavení', href: '/admin/settings', icon: Settings },
  ],
  commandGroups: ['Stránky', 'Akce'],
  commands: [
    { id: 'dashboard', label: 'Dashboard', icon: Home, href: '/admin', group: 'Stránky' },
    { id: 'clients', label: 'Klienti', icon: Users, href: '/admin/clients', group: 'Stránky' },
    { id: 'progress', label: 'Progress', icon: TrendingUp, href: '/admin/progress', group: 'Stránky' },
    { id: 'referrals', label: 'Doporučení', icon: Gift, href: '/admin/referrals', group: 'Stránky' },
    { id: 'sessions', label: 'Sessions', icon: Calendar, href: '/admin/sessions', group: 'Stránky' },
    { id: 'classes', label: 'Skupinové lekce', icon: LayoutGrid, href: '/admin/classes', group: 'Stránky' },
    { id: 'packages', label: 'Balíčky', icon: Package, href: '/admin/packages', group: 'Stránky' },
    { id: 'subscriptions', label: 'Předplatné', icon: RefreshCw, href: '/admin/subscriptions', group: 'Stránky' },
    { id: 'invoices', label: 'Faktury', icon: FileText, href: '/admin/invoices', group: 'Stránky' },
    { id: 'expenses', label: 'Výdaje', icon: Receipt, href: '/admin/expenses', group: 'Stránky' },
    { id: 'analytics', label: 'Analytika', icon: BarChart3, href: '/admin/analytics', group: 'Stránky' },
    { id: 'reports', label: 'Reporty', icon: FileBarChart, href: '/admin/reports', group: 'Stránky' },
    { id: 'email-sequences', label: 'Email sekvence', icon: Mail, href: '/admin/email-sequences', group: 'Stránky' },
    { id: 'templates', label: 'Šablony tréninků', icon: ClipboardList, href: '/admin/templates', group: 'Stránky' },
    { id: 'schedule-templates', label: 'Šablony rozvrhu', icon: CalendarClock, href: '/admin/schedule-templates', group: 'Stránky' },
    { id: 'settings', label: 'Nastavení', icon: Settings, href: '/admin/settings', group: 'Stránky' },
    { id: 'new-client', label: 'Nový klient', icon: Plus, href: '/admin/clients?action=new', group: 'Akce', keywords: ['nový', 'přidat'] },
  ],
}
